### PR TITLE
Updated some incredible codes

### PR DESCRIPTION
**Pull request by AH-dark**
Refactor the css file with less to better reflect the structure.
Changed the cdn url.

I don’t understand why it is mandatory to add `/usr/theme/akina` after the CDN URL filled in by the user.

### CODE REVIEW

**Comment by AH-dark** [comment]
In addition, I have included your topic in my personal project Source Storage, please refer to <https://ahdark.com/source/post-10.shtml> for details. 
For more information about my personal project, please refer to <https://ahdark.com/source/>.

**Comment by Zisbusy** [comment]
保持CDN资源 与源站资源的 URL 一致，提高兼容性，以确保某些厂商的整站CDN正常使用。

**Comment by AH-dark** [comment]
> 保持CDN资源 与源站资源的 URL 一致，提高兼容性，以确保某些厂商的整站CDN正常使用。

问题在于，这是没有必要的。
例如这样就无法使用jsdelivr加速服务等。
而且若是不保证一致也不会使得无法正常使用只需用户自行填写带目录关系的链接即可。

**Comment by Zisbusy** [comment]
https://github.com/Zisbusy/Jsdelivr-CDN

**Comment by AH-dark** [comment]
> https://github.com/Zisbusy/Jsdelivr-CDN

实话说，完全没有必要，反而降低了用户的可选择性

**Pull request closed without merging**
